title: John K. Hancock's Project Portfolio # your name (or website title) here
logo: "/images/1546731251843.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>MBA, PMP, CSM (He/Him)<br>
  Second description 
  <br>Master of Data Science CUNY 2021<br>
  <a href="https://www.linkedin.com/in/john-k-hancock-mba-pmp/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
